version: 2.1

jobs:
  #
  # Test 1 & Test 2
  #
  test-static-code-and-linting:
    machine:
      image: ubuntu-1604:201903-01
      # This job has been blocked because Docker Layer Caching is not available on your plan.
      # Please upgrade to continue building.
      # Note: you will need to push a new commit or call the API to rerun the pipeline.
      docker_layer_caching: false

    steps:
      - checkout

      - run: pwd
      - run: ls -ltra
      - run: git branch

      - run:
          name: test1-terraform-format
          command: make format-check

      - run:
          name: Configure awscli
          command: |
            echo "AWS_ACCESS_KEY_ID - $AWS_ACCESS_KEY_ID"
            echo "AWS_PROFILE_NAME - $AWS_PROFILE_NAME"

            # AWS defautl awscli profile
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set region us-east-1
            aws configure set output json

            # AWS dev awscli profile
            aws configure set role_arn arn:aws:iam::$AWS_ACCOUNT_ID_SHARED:role/DeployMaster --profile $AWS_PROFILE_NAME
            aws configure set source_profile default --profile $AWS_PROFILE_NAME

      - run:
          name: test2-terraform-linting
          command: make tflint-deep

  #
  # Release
  #
  release-patch-with-changelog:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: false

    steps:
      - checkout

      - run: pwd
      - run: ls -ltra
      - run: git branch

      - run:
          name: release-patch-with-changelog-circleci
          command: |
            if git status | grep 'nothing to commit, working tree clean'; then
              echo "==============================================================================================="
              echo "release-patch-with-changelog-circleci"
              echo "==============================================================================================="
              git config --global user.email "$GIT_USER_EMAIL"
              git config --global user.name "$GIT_USER_NAME"
              make -f Makefile.release release-patch-with-changelog-circleci
            else
              echo "==============================================================================================="
              echo "Changes in working directory pending to be pushed - please check 'git status' cmd output below "
              echo "==============================================================================================="
              echo "$(git status)"
              echo "==============================================================================================="
            fi

#
# Jobs workflow
#
workflows:
  version: 2
  test_and_release:
    jobs:
      - test-static-code-and-linting:
          context: binbashar-org-global-context
          filters:
            branches:
             ignore: # only branches matching the below regex filters will run
               - master
      - release-patch-with-changelog:
          context: binbashar-org-global-context
          filters:
            branches:
             only: # only branches matching the below regex filters will run
               - master
